
from app.api.IA_Agent.fake import IAAgentFake


class PromptService:

  def __init__(self) -> None:
    """
    Initialize the PromptService.
    This service is responsible for handling prompts and interacting with IA Agents.
    """
    self.__agent = IAAgentFake()

  async def get_prompt(self, prompt : str) -> str:
    """
      Process a prompt using the IA Agent and return the response.
      Args:
          prompt (str): The input prompt to process.
      Returns:
          str: The response generated by the IA Agent.
    """
    return self.__agent.execute_prompt(prompt)