
from abc import ABC, abstractmethod

class IAAgentBase(ABC):

  @abstractmethod
  def __init__(self):
    pass

  @abstractmethod
  def execute_prompt(self, message: str) -> str:
    """
    Process a message and return a response.
    Args:
        message (str): The input message to process.
    Returns:
        str: The response generated by the agent.
    """
    pass

  @abstractmethod
  def get_name(self) -> str:
    """
    Get the name of the IA Agent.
    Returns:
        str: The name of the agent.
    """
    pass